protected/controllers/UserController.php
<?php

class UserController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/column2';
    //Yii::app()->params['registerClose'] = '2014-04-01 23:59:59';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform
                'actions'=>array('index','update','showimage','pdf','superuser','allpic','list','score','editfile','finduser'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('view'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'actions'=>array('delete'),
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        if($_SESSION["isNotSuperuser"]!='false'){
            throw new CHttpException(404,'The requested page does not exist.');
        }
        $this->layout='columnSuper';
        $model=$this->loadModel($id);

        $this->performAjaxValidation($model);

        if(isset($_POST['User']))
        {
            $model->attributes=$_POST['User'];


            if($model->save())
                $this->redirect(array('/user/view', 'id'=>$id));//'uid'=>$model->uid
        }
        $this->render('view',array(
            'model'=>$model,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $this->header="Register New User";
        $model=User::model()->findByPk(Yii::app()->user->id);
        if(!Yii::app()->user->isGuest){
            if($model!=null){
                $this->redirect(array('/user'));
            }
            else{

                $model=new User;
                // Uncomment the following line if AJAX validation is needed
                $this->performAjaxValidation($model);
                if(isset($_POST['User']))
                {
                    $model->attributes=$_POST['User'];
                    $model->regisip=Yii::app()->request->userHostAddress;
                    $model->username=Yii::app()->user->id;
                    if(isset(Yii::app()->session['fbeauth']['birthday'])){
                        $bd=Yii::app()->session['fbeauth']['birthday'];
                        $model->birthdate=substr($bd,-4)."-".substr($bd,-7,2)."-".substr($bd,0,2);
                    }


                    if($model->save())
                        $this->redirect(array('/user'));//$this->redirect(array('/site/login'));
                }

                $this->render('create',array(
                    'model'=>$model,
                ));
                
            }
        }else{
            $this->redirect(array('/site/login'));
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($uid)
    {

        //FBSendNotice::sendNotice('1449083385318999','5f7eea8cee76108d8c6367c53b7d55ce');
        if($_SESSION["isNotSuperuser"] =='false'||$uid==Yii::app()->user->id) {
            if($_SESSION["isNotSuperuser"] =='false')
                $this->layout='columnSuper';

            $model=$this->loadModel($uid);

            // Uncomment the following line if AJAX validation is needed
            $this->performAjaxValidation($model);

            if(isset($_POST['User']))
            {
                $model->attributes=$_POST['User'];


                if($model->save())
                    $this->redirect(array('/user'));//'uid'=>$model->uid
            }

            $this->render('update',array(
                'model'=>$model,
            ));

        }else{
            throw new CHttpException(404,'The requested page does not exist.');
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($uid)
    {
        $this->loadModel($uid)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $_SESSION["isNotSuperuser"] = 'true';
        /*$dataProvider=new CActiveDataProvider('User');
        $this->render('index',array('dataProvider'=>$dataProvider,));*/
        $this->render('index',array());
    }

    /**
     * Manages all models.
     */
    public function actionSuperuser($pwd)
    {
    	$this->layout='columnSuper';
    	//if(Yii::app()->user->id=='100000154047359')
        if($pwd=='7pmaccsec')
    	{
            $_SESSION["isNotSuperuser"] = 'false';
			$model=new User('search');
			$model->unsetAttributes();  // clear any default values
            if(isset($_POST['FORMNAME']))
                $this->redirect(array('user/finduser','name'=>$_POST['FORMNAME']['fname']));
			/*if(isset($_GET['User']))
			$model->attributes=$_GET['User'];*/

			$this->render('admin',array(
				'model'=>$model,
			));
	    }else{
            throw new CHttpException(404,'The requested page does not exist.');
        }
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return User the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=User::model()->findByPk($id);
        //if($model===null)
        //    throw new CHttpException(404,'The requested page does not exist.');
        //if($model===null)
        //    $this->redirect(array('user/create')); //throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param User $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }



    public function actions()
    {
        return array(
            'captcha'=>array(
                'class'=>'CCaptchaAction',
                'backColor'=>0xFFFFFF,
                'transparent'=>true,
                'testLimit'=>1,
                'foreColor'=>0x348017
            ),
        );


    }

    public function actionShowimage($filename = false)
    {
        //$this->render('showimage',array('filename'=>$filename));
        $fileUpload=Upload::model()->findByPk($filename);

        if(Yii::app()->user->id==$fileUpload->create_username||$_SESSION["isNotSuperuser"] =='false')
            $filename=$fileUpload->file;
        else{
            throw new CHttpException(401,'Unauthorized.');
        }

        if ($filename)
        {
            $path =  Yii::getPathOfAlias('application.uploads'). '/';
            if (file_exists($path. $filename))
            {
                $file=@file_get_contents($path. $filename);
                if($file)
                {
                    Yii::app()->request->sendFile($filename,$file);
                }else{
                    throw new CHttpException(403,'Forbidden.');
                }
            } else {
                echo $filename.", File not found!";
            }
        }
        //return null;

    }

    public function actionPdf($id)
    {
        if(Yii::app()->user->id!=$id&&$_SESSION["isNotSuperuser"] !='false')
            throw new CHttpException(401,'Unauthorized.');

        $model=$this->loadModel($id);
        $mPDF1 = Yii::app()->ePdf->mpdf('th', 'A4');
        $mPDF1->useSubstitutions = true;
        $mPDF1->WriteHTML($this->renderPartial('pdf', array('model'=>$model), true));
        $mPDF1->SetAuthor("CE KMITL 51");
        $mPDF1->SetCreator('CE SMART CAMP7');
        $mPDF1->SetTitle('ใบสมัครค่าย');
        $mPDF1->SetSubject('CESC : Quiz');
        $mPDF1->Output('CE Smart Camp 7.pdf','I');

    }

    public function actionAllpic()
    {
        $this->layout='columnSuper';
        if(Yii::app()->user->id==100000154047359){

            $criteria=new CDbCriteria();
            $criteria->condition = "istester=0 AND gender='หญิง'";
            $dataProvider=new CActiveDataProvider('User', array(
                'criteria'=>$criteria,
                'sort'=>array(
                    'defaultOrder'=>'uid DESC',
                    ),
                'pagination'=>array(
                    'pageSize'=>'20'
                    ),

                ));

protected/views/layouts/column0.php
<!DOCTYPE HTML> 
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="language" content="th" />

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css">
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.min.js"></script> 
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('body').fadeIn();
            $('a').click(function (e) {
                window.goto = $(this).attr("href");
                $('body').fadeOut('fast', function () {
                    document.location.href = window.goto;
                });
                e.preventDefault();
            });
        });
    </script>

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <style>
    @font-face {
    font-family: 'WDB_Bangna';
    src: url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.eot');
    src: url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.eot?#iefix') format('embedded-opentype'),
         url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.woff') format('woff'),
         url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.ttf') format('truetype'),
         url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.svg') format('svg');
    font-weight: normal;
    font-style: normal;
    }
    
    .navbar-fixed-top
    {
        max-height:160px;
    }
    body
    {
        font-family:"WDB_Bangna";
        background-color:#a3d4f0;
    }   

    .panel-heading a,span
    {
        font-size:1.4em;
    }

    .panel-body
    {
        font-size:1.3em;
    }
    h1,h2,h3
    {
        font-family:"WDB_Bangna" !important;
    }

    .navbar-nav>li
    {
        border-bottom:solid #f8f8f8 4px;
        font-size:1.5em;
    }
    .navbar-nav>li:hover>a 
    {
        border-bottom:solid #2980b9 4px;
        background-color:#f8f8f8;
        color:#2980b9 !important;
    }

    li.active>a
    {
        background-color:#f8f8f8 !important;
        border-bottom:solid #2980b9 4px;
        color:#2980b9 !important;
    }
    </style>
</head>
<body style=" padding-top: 150px; ">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <div class="navbar-brand" >
                    <?php echo CHtml::image("/images/logoCE.png","",$htmlOptions=array('style'=>'width:100px; height:100px;'))?>
                    </div>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <h1 style="font-size:1.8em;"><?php echo $this->header; ?></h1>

        <?php

            $this->widget('zii.widgets.CMenu',array(
                'items'=>array(
                    array('label'=>'Home', 'url'=>array('/site/index')),
                    //array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
                    //array('label'=>'Contact', 'url'=>array('/site/contact')),
                    array('label'=>'ข้อมูลส่วนตัว', 'url'=>array('/user/index'), 'visible'=>!Yii::app()->user->isGuest,),
                    array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
                ),
                'htmlOptions'=>array('class'=>'nav navbar-nav'),
            ));
        
        ?>
    </div><!-- /.navbar-collapse -->
</nav>

<div class="container" style="padding-top:80px;">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">

        <div class="panel panel-info">
        
 
            <div class="panel-heading hidden">
                                  
                    <?php if(isset($this->breadcrumbs)):?>
                        <?php
                        	$this->widget('zii.widgets.CBreadcrumbs', array('links'=>$this->breadcrumbs,)); 
                        ?>
                    <?php endif?>

                
            </div>

            <div class="panel-body">
                <?php echo $content; ?>
            </div>

        </div>
    </div>

</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46162880-1', 'cesmartcamp.com');
  ga('send', 'pageview');

</script>
</body>
</html>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ 
$model2=null;
if(!Yii::app()->user->isGuest)
    $model2=$this->loadModel(Yii::app()->user->id);//load data into Model
?>
<!DOCTYPE HTML> 
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="language" content="th" />

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css">
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.min.js"></script> 
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <style>
    @font-face {
    font-family: 'WDB_Bangna';
    src: url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.eot');
    src: url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.eot?#iefix') format('embedded-opentype'),
         url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.woff') format('woff'),
         url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.ttf') format('truetype'),
         url('<?php echo Yii::app()->request->baseUrl; ?>/css/font/WDB_Bangna.svg') format('svg');
    font-weight: normal;
    font-style: normal;
    }
    
    .navbar-fixed-top
    {
        max-height:160px;
    }
    body
    {
        font-family:"WDB_Bangna";
        background-color:#a3d4f0;
    }   

    .panel-heading a,span
    {
        font-size:1.4em;
    }

    .panel-body
    {
        font-size:1.3em;
    }
    h1,h2,h3
    {
        font-family:"WDB_Bangna" !important;
    }

    .navbar-nav>li
    {
        border-bottom:solid #f8f8f8 4px;
        font-size:1.5em;
    }
    .navbar-nav>li:hover>a 
    {
        border-bottom:solid #2980b9 4px;
        background-color:#f8f8f8;
        color:#2980b9 !important;
    }

    li.active>a
    {
        background-color:#f8f8f8 !important;
        border-bottom:solid #2980b9 4px;
        color:#2980b9 !important;
    }
    .open>a
    {
        border-bottom:solid #2980b9 4px;
    }
    .dropdown-menu
    {
        width:100%;
    }
    .dropdown-menu li
    {
        font-size:1.3em;
    }
    .dropdown-menu li:hover>a
    {
        color:#2980b9;
    }
    </style>
</head>
<body style=" padding-top: 150px; " id="testhash">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <div class="navbar-brand" >
                    <?php echo CHtml::image("/images/logoCE.png","",$htmlOptions=array('style'=>'width:100px; height:100px;'))?>
                    <?php
                        if(!Yii::app()->user->isGuest){
                            $headers = get_headers('http://graph.facebook.com/'.Yii::app()->user->id.'/picture?width=100&height=100',1);
                            echo CHtml::image($headers['Location'],"", $htmlOptions=array('class'=>'img-thumbnail') );
                        }
                    ?></div>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <h1 style="font-size:1.8em;">
    	<strong>
	    <?php
	    	echo $this->header;

            //echo "<abbr title=\"หากต้องการเปลี่ยนสาขาสามารถแจ้งได้ที่แฟนเพจจ้า\">";
	    	if(!Yii::app()->user->isGuest&&$model2!=null){
	    		$camp=$model2->camp;
		        if($camp=="Robot"){
		            echo " <small>(Robot)</small>";
		        }else if($camp=="Network"){
		            echo " <small>(Network)</small>";
		        }
	    	}
            //echo "</abbr>";


	    ?>
		</strong></h1>
    <h2 style="font-size:1.6em;"><?php if(!Yii::app()->user->isGuest&&$model2!=null){
    		if($model2->filestatus==0){
                if($model2->surname!='' &&
                    $model2->nickname!='' &&
                    $model2->age!='' &&
                    $model2->birthdate!='' &&
                    $model2->address!='' &&
                    $model2->phone_mobile!='' &&
                    $model2->school!='' &&
                    $model2->branch!='' &&
                    $model2->gpa!='' &&
                    $model2->class!='' &&
                    $model2->region!='' &&
                    $model2->student_pic!='' &&
                    $model2->other_pic!='' &&
                    $model2->sheet_studentid!='' &&
                    $model2->sheet_parent!='' &&
                    $model2->sheet_gen1!='' &&
                    $model2->sheet_gen2!='' &&
                    $model2->sheet_gen3!='' &&
                    $model2->address_province!='' &&
                    $model2->address_postcode!='' &&
                    $model2->parent_name!='' &&
                    $model2->parent_phone!='' &&
                    $model2->thai_id!='' &&
                    $model2->foundby!='')
                {
                    if($model2->camp=='Robot'){
                        if(($model2->sheet_rb1!=''&&
                                $model2->sheet_rb2!=''&&
                                $model2->sheet_rb3!=''&&
                                $model2->sheet_rb4!='')||
                            ($model2->sheet_nw1!=''&&
                            $model2->sheet_nw2!=''&&
                            $model2->sheet_nw3!='')){
                            echo "<p class=\"text-info\">เอกสารรอการตรวจสอบ";
                        }
                    }
                }else{
                    echo "<p class=\"text-danger\">เอกสารยังไม่สมบูรณ์ &#x2716; ";
                }
                echo "<small>".$model2->notice." </small>";
                if($model2->byMail==1)
                    echo "<small>, ได้รับเอกสารทางไปรษณีย์ &#10004;</small>";
                echo "</p>";
    		}else{
    			echo "<p class=\"text-success\">เอกสารสมบูรณ์ &#10004; <small>รอประกาศผลการคัดเลือก 10 เม.ย.</small>";
                if($model2->byMail==1)
                    echo "<small>, ได้รับเอกสารทางไปรษณีย์ &#10004;</small>";
                echo "</p>";
    			
    		}
    		/*
    		☐ (0x2610  in Unicode hexadecimal [HTML decimal: &#9744;]): an empty (unchecked) checkbox
			☑ (0x2611  [HTML decimal: &#9745;]): the checked version of the previous checkbox
			✓ (0x2713  [HTML decimal: &#10003;])
			✔ (0x2714  [HTML decimal: &#10004;])
    		*/

    	} ?></h2>
        <?php

        if(!Yii::app()->user->isGuest && $model2!=null){
            $this->widget('zii.widgets.CMenu',array(
                //'activeCssClass'=>'btn btn-primary',
                'items'=>array(
                    array('label'=>'หน้าแรก', 'url'=>array('/site/index')),
                    //array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
                    //array('label'=>'Contact', 'url'=>array('/site/contact')),
                    array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
                    //array('label'=>'Regis', 'url'=>array('/user/create'), 'visible'=>!Yii::app()->user->isGuest),
                    array('label'=>'ข้อมูลส่วนตัว', 'url'=>array('/user/index'), 'visible'=>!Yii::app()->user->isGuest,),
                    array('label'=>'แก้ไขข้อมูล',  'url'=>array('/user/update', 'uid'=>$model2->username),        'visible'=>!Yii::app()->user->isGuest),
                    array('label'=>'ดาวน์โหลดเอกสาร', 'url'=>'#',                                    'visible'=>!Yii::app()->user->isGuest,'items'=>array(
                    array('label'=>'ใบสมัคร', 'url'=>array('user/pdf','id'=>$model2->username), 'linkOptions'=>array('target'=>'_blank'),                               'visible'=>!Yii::app()->user->isGuest),
                    array('label'=>'คำถาม', 'url'=>($model2->camp=="Robot"?'/Doc/RobotQuiz.pdf':'/Doc/NetworkQuiz.pdf'),  'linkOptions'=>array('target'=>'_blank'),  'visible'=>!Yii::app()->user->isGuest),
                    //('.Yii::app()->user->name.')
                ),'itemOptions'=>array('class'=>'dropdown'), 'linkOptions'=>array('class'=>'dropdown-toggle','data-toggle'=>'dropdown' ,'target'=>'_blank'), 'submenuOptions'=>array('class'=>'dropdown-menu')),
                    array('label'=>'Logout ',       'url'=>array('/site/logout'),                           'visible'=>!Yii::app()->user->isGuest), 
                    //('.Yii::app()->user->name.')
                ),
                'htmlOptions'=>array('class'=>'nav navbar-nav cescul'),
            ));
        }else{
            $this->widget('zii.widgets.CMenu',array(
                //'activeCssClass'=>'btn btn-primary',
                'items'=>array(
                    array('label'=>'Home', 'url'=>array('/site/index')),
                    //array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
                    //array('label'=>'Contact', 'url'=>array('/site/contact')),
                    array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
                ),
                'htmlOptions'=>array('class'=>'nav navbar-nav'),
            ));
        }
        ?>
    </div><!-- /.navbar-collapse -->
</nav>

<div class="container" style="padding-top:80px;">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">

        <div class="panel panel-info">
        
 
            <div class="panel-heading hidden">
                                  
                    <?php if(isset($this->breadcrumbs)):?>
                        <?php
                        	$this->widget('zii.widgets.CBreadcrumbs', array('links'=>$this->breadcrumbs,)); 
                        ?>
                    <?php endif?>

                
            </div>

            <div class="panel-body">
                <?php echo $content; ?>
            </div>

        </div>
    </div>

</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46162880-1', 'cesmartcamp.com');
  ga('send', 'pageview');

</script>
</body>
</html>

protected/views/layouts/mainOld.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="language" content="th" />

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/reset-min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/animations.css">
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/styleEx.css">
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bjqs.css">
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.stellar.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/waypoints.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bjqs-1.3.min.js"></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jsEx.js"></script>
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
    <?php
    //TODO(ziko):Head,Menu,Breacrum HERE
    echo $content;
    ?>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-46162880-1', 'kmi.tl');
        ga('send', 'pageview');

    </script>
</body>
</html>