protected/controllers/UserController.php
<?php

class UserController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/column2';
    //Yii::app()->params['registerClose'] = '2014-04-01 23:59:59';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform
                'actions'=>array('index','update','showimage','pdf','superuser','allpic','list','score','editfile','finduser'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('view'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'actions'=>array('delete'),
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        if($_SESSION["isNotSuperuser"]!='false'){
            throw new CHttpException(404,'The requested page does not exist.');
        }
        $this->layout='columnSuper';
        $model=$this->loadModel($id);

        $this->performAjaxValidation($model);

        if(isset($_POST['User']))
        {
            $model->attributes=$_POST['User'];


            if($model->save())
                $this->redirect(array('/user/view', 'id'=>$id));//'uid'=>$model->uid
        }
        $this->render('view',array(
            'model'=>$model,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $this->header="Register New User";
        $model=User::model()->findByPk(Yii::app()->user->id);
        if(!Yii::app()->user->isGuest){
            if($model!=null){
                $this->redirect(array('/user'));
            }
            else{

                $model=new User;
                // Uncomment the following line if AJAX validation is needed
                $this->performAjaxValidation($model);
                if(isset($_POST['User']))
                {
                    $model->attributes=$_POST['User'];
                    $model->regisip=Yii::app()->request->userHostAddress;
                    $model->username=Yii::app()->user->id;
                    if(isset(Yii::app()->session['fbeauth']['birthday'])){
                        $bd=Yii::app()->session['fbeauth']['birthday'];
                        $model->birthdate=substr($bd,-4)."-".substr($bd,-7,2)."-".substr($bd,0,2);
                    }


                    if($model->save())
                        $this->redirect(array('/user'));//$this->redirect(array('/site/login'));
                }

                $this->render('create',array(
                    'model'=>$model,
                ));
                
            }
        }else{
            $this->redirect(array('/site/login'));
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($uid)
    {

        //FBSendNotice::sendNotice('1449083385318999','5f7eea8cee76108d8c6367c53b7d55ce');
        if($_SESSION["isNotSuperuser"] =='false'||$uid==Yii::app()->user->id) {
            if($_SESSION["isNotSuperuser"] =='false')
                $this->layout='columnSuper';

            $model=$this->loadModel($uid);

            // Uncomment the following line if AJAX validation is needed
            $this->performAjaxValidation($model);

            if(isset($_POST['User']))
            {
                $model->attributes=$_POST['User'];


                if($model->save())
                    $this->redirect(array('/user'));//'uid'=>$model->uid
            }

            $this->render('update',array(
                'model'=>$model,
            ));

        }else{
            throw new CHttpException(404,'The requested page does not exist.');
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($uid)
    {
        $this->loadModel($uid)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $_SESSION["isNotSuperuser"] = 'true';
        /*$dataProvider=new CActiveDataProvider('User');
        $this->render('index',array('dataProvider'=>$dataProvider,));*/
        $this->render('index',array());
    }

    /**
     * Manages all models.
     */
    public function actionSuperuser($pwd)
    {
    	$this->layout='columnSuper';
    	//if(Yii::app()->user->id=='100000154047359')
        if($pwd=='7pmaccsec')
    	{
            $_SESSION["isNotSuperuser"] = 'false';
			$model=new User('search');
			$model->unsetAttributes();  // clear any default values
            if(isset($_POST['FORMNAME']))
                $this->redirect(array('user/finduser','name'=>$_POST['FORMNAME']['fname']));
			/*if(isset($_GET['User']))
			$model->attributes=$_GET['User'];*/

			$this->render('admin',array(
				'model'=>$model,
			));
	    }else{
            throw new CHttpException(404,'The requested page does not exist.');
        }
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return User the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=User::model()->findByPk($id);
        //if($model===null)
        //    throw new CHttpException(404,'The requested page does not exist.');
        //if($model===null)
        //    $this->redirect(array('user/create')); //throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param User $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }



    public function actions()
    {
        return array(
            'captcha'=>array(
                'class'=>'CCaptchaAction',
                'backColor'=>0xFFFFFF,
                'transparent'=>true,
                'testLimit'=>1,
                'foreColor'=>0x348017
            ),
        );


    }

    public function actionShowimage($filename = false)
    {
        //$this->render('showimage',array('filename'=>$filename));
        $fileUpload=Upload::model()->findByPk($filename);

        if(Yii::app()->user->id==$fileUpload->create_username||$_SESSION["isNotSuperuser"] =='false')
            $filename=$fileUpload->file;
        else{
            throw new CHttpException(401,'Unauthorized.');
        }

        if ($filename)
        {
            $path =  Yii::getPathOfAlias('application.uploads'). '/';
            if (file_exists($path. $filename))
            {
                $file=@file_get_contents($path. $filename);
                if($file)
                {
                    Yii::app()->request->sendFile($filename,$file);
                }else{
                    throw new CHttpException(403,'Forbidden.');
                }
            } else {
                echo $filename.", File not found!";
            }
        }
        //return null;

    }

    public function actionPdf($id)
    {
        if(Yii::app()->user->id!=$id&&$_SESSION["isNotSuperuser"] !='false')
            throw new CHttpException(401,'Unauthorized.');

        $model=$this->loadModel($id);
        $mPDF1 = Yii::app()->ePdf->mpdf('th', 'A4');
        $mPDF1->useSubstitutions = true;
        $mPDF1->WriteHTML($this->renderPartial('pdf', array('model'=>$model), true));
        $mPDF1->SetAuthor("CE KMITL 51");
        $mPDF1->SetCreator('CE SMART CAMP7');
        $mPDF1->SetTitle('ใบสมัครค่าย');
        $mPDF1->SetSubject('CESC : Quiz');
        $mPDF1->Output('CE Smart Camp 7.pdf','I');

    }

    public function actionAllpic()
    {
        $this->layout='columnSuper';
        if(Yii::app()->user->id==100000154047359){

            $criteria=new CDbCriteria();
            $criteria->condition = "istester=0 AND gender='หญิง'";
            $dataProvider=new CActiveDataProvider('User', array(
                'criteria'=>$criteria,
                'sort'=>array(
                    'defaultOrder'=>'uid DESC',
                    ),
                'pagination'=>array(
                    'pageSize'=>'20'
                    ),

                ));

protected/views/user/_list.php
<?php
/* @var $this UserController */
/* @var $data User */
?>

<div class="col-md-3">
	    <?php
	        echo CHtml::link($data->surname,array('user/view','id'=>$data->username),array('target'=>'_blank'));
	    ?>
</div>

protected/views/user/_search.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'uid'); ?>
		<?php echo $form->textField($model,'uid'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'regisTime'); ?>
		<?php echo $form->textField($model,'regisTime'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'gender'); ?>
		<?php echo $form->textField($model,'gender'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surname'); ?>
		<?php echo $form->textField($model,'surname',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nickname'); ?>
		<?php echo $form->textField($model,'nickname',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'age'); ?>
		<?php echo $form->textField($model,'age'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'birthdate'); ?>
		<?php echo $form->textField($model,'birthdate'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'address'); ?>
		<?php echo $form->textArea($model,'address',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'phone_home'); ?>
		<?php echo $form->textField($model,'phone_home',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'phone_mobile'); ?>
		<?php echo $form->textField($model,'phone_mobile',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'school'); ?>
		<?php echo $form->textField($model,'school',array('size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'branch'); ?>
		<?php echo $form->textField($model,'branch',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'gpa'); ?>
		<?php echo $form->textField($model,'gpa',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'class'); ?>
		<?php echo $form->textField($model,'class'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'region'); ?>
		<?php echo $form->textField($model,'region'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'allergy'); ?>
		<?php echo $form->textArea($model,'allergy',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'allergy_drug'); ?>
		<?php echo $form->textArea($model,'allergy_drug',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'allergy_food'); ?>
		<?php echo $form->textArea($model,'allergy_food',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'camp'); ?>
		<?php echo $form->textField($model,'camp'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_view.php
<?php
/* @var $this UserController */
/* @var $data User */
?>

<div class="col-md-3">
	<a href="https://www.facebook.com/<?php echo $data->username;  ?>">
	    <?php
	        $headers = get_headers('http://graph.facebook.com/'.$data->username.'/picture?width=200&height=200',1);
	        echo CHtml::image($headers['Location'],"", $htmlOptions=array('class'=>'img-thumbnail') );
	    ?>
    </a>
</div>

protected/views/user/admin.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#user-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Users</h1>

<?php
echo CHtml::link("<b>จำนวนน้องที่ส่งเอกสารเรียบร้อยแล้ว (คลิกเพื่อดู)</b><br/>",array('user/list'),array('target'=>'_blank'));
?>
Robot :
<?php
	$count = User::Model()->count("filestatus=1 AND camp='Robot'");
	echo $count." คน<br/>";
?>
Network :
<?php

	$count = User::Model()->count("filestatus=1 AND camp='Network'");
	echo $count." คน<br/>";
?>

<br/>
<b>จำนวนน้องที่รอการตรวจใบสมัคร :</b>
<?php
	$sql = "SELECT COUNT(*) FROM cesc_user WHERE nickname <> '' AND sheet_gen3 <> '' AND filestatus=0";
	$count = Yii::app()->db->createCommand($sql)->queryScalar();
	echo $count." คน<br/>";
?>

<?php
	$taProvider=new CActiveDataProvider('User',array(
                'criteria'=>array(
				        'condition'=>"nickname <> '' AND sheet_gen3 <> '' AND filestatus=0",
				),  
            ));
	$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$taProvider,
	'itemView'=>'_list',
	));
?>
<hr/>
<?php
	echo(CHtml::beginForm());	
	echo(CHtml::label('ชื่อที่ต้องการค้น', 'name'));
	echo CHtml::textField('FORMNAME[fname]');
	echo(CHtml::submitButton('Search'));
	echo(CHtml::endForm());
?>
<hr/>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'enableSorting'=>'true',
	'columns'=>array(
		'uid',
		'nickname',
        'gender',
		'class',
		'camp',

		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/user/allpic.php
<?php
/* @var $this UploadController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Photo',
);

?>

<h1>Uploads</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/user/finduser.php
<?php
    $this->widget('zii.widgets.CListView', array(
        'dataProvider'=>$dataProvider,
        'itemsCssClass'=>'list-view row',
        'itemView'=>'_list',
    ));
?>

protected/views/user/view.php
<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->username,
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	//array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Update User', 'url'=>array('update', 'uid'=>$model->username)),
	//array('label'=>'Delete User', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->username),'confirm'=>'Are you sure you want to delete this item?')),
	//array('label'=>'Manage User', 'url'=>array('admin')),
);
?>
<div class="row">
	<div class="col-md-8">
		<h1>View User #<?php echo $model->username; ?></h1>
		<h3><?php echo $model->filestatus?"<p class=\"text-success\">เอกสารครบ &#10004;</p>":"<p class=\"text-danger\">เอกสารไม่ครบ &#x2716;</p>" ?></h3>
		<?php echo CHtml::link("แก้ไขข้อมูล",array('user/update','uid'=>$model->username),array('target'=>'_blank'));?>
	</div>
	<div class="col-md-4">
		<a href="https://www.facebook.com/<?php echo $model->username;  ?>">
			<?php
				$headers = get_headers('http://graph.facebook.com/'.$model->username.'/picture?width=200&height=200',1);
				echo CHtml::image($headers['Location'],"", $htmlOptions=array('class'=>'img-thumbnail') );
			?>
		</a>
	</div>
</div>
<hr/>
เอกสารที่ส่งมาแล้ว (<?php echo CHtml::link("ให้คะแนน",array('user/score','id'=>$model->username),array('target'=>'_blank'));?>)<br/>
<div class="row">
	<div class="col-sm-3">
		ใบสมัคร
	</div>
	<div class="col-sm-3">
		<?php echo CHtml::link("ดู",array('user/pdf','id'=>$model->username),array('target'=>'_blank'))."<br/>"; ?>
	</div>
</div>
<?php
echo "<div class=\"row\">";
echo "<div class=\"col-sm-3\">";
echo CHtml::encode($model->getAttributeLabel('student_pic'));
echo " : ";
if($model->student_pic!=''){
	echo CHtml::link("ดู",array('user/showimage','filename'=>$model->student_pic),array('target'=>'_blank'))."<br/>";
}
echo "</div>";

echo "<div class=\"col-sm-3\">";
echo CHtml::encode($model->getAttributeLabel('other_pic'));
echo " : ";
if($model->other_pic!=''){
	echo CHtml::link("ดู",array('user/showimage','filename'=>$model->other_pic),array('target'=>'_blank'))."<br/>";
}
echo "</div>";

echo "<div class=\"col-sm-3\">";
echo "สำเนาบัตร";
echo " : ";
if($model->sheet_studentid!=''){
	echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_studentid),array('target'=>'_blank'))."<br/>";
}
echo "</div>";

echo "<div class=\"col-sm-3\">";
echo CHtml::encode($model->getAttributeLabel('sheet_parent'));
echo " : ";
if($model->sheet_parent!=''){
	echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_parent),array('target'=>'_blank'))."<br/>";
}
echo "</div>";

echo "<div class=\"col-sm-3\">";
echo CHtml::encode($model->getAttributeLabel('sheet_gen1'));
echo " : ";
if($model->sheet_gen1!=''){
	echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_gen1),array('target'=>'_blank'))."<br/>";
}
echo "</div>";
echo "<div class=\"col-sm-3\">";
echo "หน้า 2 : ";
if($model->sheet_gen2!=''){
	echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_gen2),array('target'=>'_blank'))."<br/>";
}
echo "</div>";
echo "<div class=\"col-sm-3\">";
echo "หน้า 3 : ";
if($model->sheet_gen3!=''){
	echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_gen3),array('target'=>'_blank'))."<br/>";
}
echo "</div>";

echo "</div>";

echo "<div class=\"row\">";
if($model->camp=="Robot"){
	echo "<div class=\"col-sm-3\">";
	echo CHtml::encode($model->getAttributeLabel('sheet_rb1'));
	echo " : ";
	if($model->sheet_rb1!=''){
		echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_rb1),array('target'=>'_blank'))."<br/>";
	}
	echo "</div>";
	echo "<div class=\"col-sm-3\">";
	echo "หน้า 2 : ";
	if($model->sheet_rb2!=''){
		echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_rb2),array('target'=>'_blank'))."<br/>";
	}
	echo "</div>";
	echo "<div class=\"col-sm-3\">";
	echo "หน้า 3 : ";
	if($model->sheet_rb3!=''){
		echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_rb3),array('target'=>'_blank'))."<br/>";
	}
	echo "</div>";
	echo "<div class=\"col-sm-3\">";
	echo "หน้า 4 : ";
	if($model->sheet_rb4!=''){
		echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_rb4),array('target'=>'_blank'))."<br/>";
	}
	echo "</div>";
}else{
	echo "<div class=\"col-sm-3\">";
	echo CHtml::encode($model->getAttributeLabel('sheet_nw1'));
	echo " : ";
	if($model->sheet_nw1!=''){
		echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_nw1),array('target'=>'_blank'))."<br/>";
	}
	echo "</div>";
	echo "<div class=\"col-sm-3\">";
	echo "หน้า 2 : ";
	if($model->sheet_nw2!=''){
		echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_nw2),array('target'=>'_blank'))."<br/>";
	}
	echo "</div>";
	echo "<div class=\"col-sm-3\">";
	echo "หน้า 3 : ";
	if($model->sheet_nw3!=''){
		echo CHtml::link("ดู",array('user/showimage','filename'=>$model->sheet_nw3),array('target'=>'_blank'))."<br/>";
	}
	echo "</div>";
}
echo "</div>";
?>
<hr/>
<div class="panel panel-danger">
	<div class="panel-heading">
		อัพเดตสถานะ
	</div>
	<div class="panel-body">
		<div class="" role="form">

		    <?php $form=$this->beginWidget('CActiveForm', array(
		        'id'=>'user-form',
		        'enableAjaxValidation'=>false,
		    )); ?>

		    <div class="form-group">
		    	<div class="row">
			    	<div class="col-sm-3">
			        <?php   echo $form->labelEx($model,'filestatus',array('class'=>'control-label')); ?>
			        </div>
			        <div class="col-sm-3">
			            <?php echo $form->dropDownList($model,'filestatus', array('0'=>'ยังไม่ได้รับ/เอกสารไม่ครบ','1'=>'ได้รับเอกสาร/เอกสารครบ'),array('class'=>'form-control')); ?>
			        </div>
			    </div>
			    <div class="row">
			    	<div class="col-sm-3">
			        <?php   echo $form->labelEx($model,'byMail',array('class'=>'control-label')); ?>
			        </div>
			        <div class="col-sm-3">
			            <?php echo $form->dropDownList($model,'byMail', array('0'=>'ไม่ได้รับเอกสารทางไปรษณีย์','1'=>'ได้รับเอกสารทางไปรษณีย์'),array('class'=>'form-control')); ?>
			        </div>
			    </div>
			    <div class="row">
			        <div class="col-sm-3">
			        	 <?php   echo $form->labelEx($model,'notice',array('class'=>'control-label')); ?>
			        </div>
			        <div class="col-sm-4">
			            <?php   echo $form->textField($model,'notice',array('class'=>'form-control','size'=>70,'maxlength'=>70,'placeholder'=>'ถ้าเรียบร้อยไม่ต้องใส่อะไร')); ?>
			        </div>		    
		    	</div>
		    	<div class="row">
			        <div class="col-sm-3">
			        	 <?php   echo $form->labelEx($model,'isPrinted',array('class'=>'control-label')); ?>
			        </div>
			        <div class="col-sm-4">
			            <?php echo $form->dropDownList($model,'isPrinted', array('0'=>'ยังไม่ได้พริ้นต์','1'=>'พริ้นต์แล้ว'),array('class'=>'form-control')); ?>
			        </div>		    
		    	</div>
		    	<hr/>
		    	<div class="row">
			        <div class="col-sm-3">
			        	 <?php   echo $form->labelEx($model,'isCesc7',array('class'=>'control-label')); ?>
			        </div>
			        <div class="col-sm-4">
			            <?php echo $form->dropDownList($model,'isCesc7', array('0'=>'NO'),array('class'=>'form-control')); ?>
			        </div>		    
			        <div class="col-sm-3">
			        	<?php
				        	if($_SESSION["isNotSuperuser"]=='false'){
					        	if($model->filestatus)
					        		echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'บันทึก',array('class'=>'btn btn-success form-group')); 
					        	else
					        		echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'บันทึก',array('class'=>'btn btn-danger form-group')); 
					        }
			        	?>
			    	</div>
		    	</div>
		    </div>
		    <?php $this->endWidget(); ?>
		</div>
	</div>
</div>
<hr/>
<h3>ข้อมูล</h3>
<?php

$this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'uid' ,
		'surname' ,
		'filestatus',
		'notice',
		'byMail',
				//'username' ,
		'camp',

		'gen1',
		'gen2',
		'gen3',
		'gen4',
		'gen5',
		'gen6',
		'gen7',
		'gen8',
		'rb1',
		'rb2',
		'rb3',
		'rb4',
		'nw1',
		'nw2',
		'nw3',
		'nw4',
		'nw5',
		'nw6',
		'nw7',
		'nw8',

		'email' ,
		'regisTime' ,
		'gender' ,
		'nickname' ,
		'age' ,
		'birthdate' ,
		'address' ,
		'phone_home' ,
		'phone_mobile' ,
		'school' ,
		'branch' ,
		'gpa' ,
		'class' ,
		'region' ,
		'allergy' ,
		'allergy_drug' ,
		'allergy_food' ,
		'camp',
		'regisip',
		'bloodtype',
		'phone_mobile_network',
		'address_province',
		'address_postcode',
		'talent',
		'not_eat',
		'parent_name',
		'parent_relation',
		'parent_phone',
		'school_province',
		'camp1',
		'camp1_uni',
		'camp2',
		'camp2_uni',
		'camp3',
		'camp3_uni',
		'disease',
		'thai_id',
		),
	));

?>